config/routes.rb
Warmup::Application.routes.draw do

  resources :users  
 

   match '/help', to: "static_pages#help"  # arranges both for a valid page at /help and a named route 
  match '/about', to: "static_pages#about"
  match '/contact', to: "static_pages#contact"
  match '/signup', to: "users#new"

   root :to => "static_pages#home"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  lastname        :string(255)
#  email           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#

class User < ActiveRecord::Base
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	attr_accessible :name, :lastname, :email, :password, :password_confirmation
	has_secure_password 
	
	validates :name, presence: true, length: { maximum: 50}
	validates :lastname, presence: true, length: { maximum: 50 }
	validates :email, presence: true, 
					  uniqueness: { case_sensitive: false },
					  format: { with: VALID_EMAIL_REGEX }

	validates :password, presence: true, length: { minimum: 5 }
	validates :password_confirmation, presence: true 

	before_save { |user| user.email = email.downcase }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def homes
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		flash[:success] = "Welcome to your profile page :)"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "IDK"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer"> 
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
    		<div class="navbar-inner">
    			<div class="container">
    ...				<%= link_to "IDK", root_path, class: "brand", id: "logo" %>
    				<nav>
    					<ul class="nav pull-right">
    						<li> <%= link_to "Home", root_path %> </li>
    						<li> <%= link_to "Help", help_path %> </li>
    						<li> <%= link_to "Sign in", '#'%> </li>
    					</ul>
    				</nav>
    			</div>
    		</div>
    	</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %> <!-- includes application.css-->
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  		
  	    <%= render 'layouts/header'%>

    	<!-- content of the page -->
  		<div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>

    		<%= yield %>
    		<%= render 'layouts/footer'%>
        <%= debug(params) if Rails.env.development? %>
    	</div>
  </body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
    <div class="alert alert-error">
		The form contains <%= pluralize(@user.errors.count, "error")%> 
	</div>
	<ul>
		<% @user.errors.full_messages.each do |error| %>
			<li> <%= error %> </li>
		<% end %>
	</ul>
</div>
<% end %> 

app/views/static_pages/about.html.erb

<% provide(:title, 'About')%>

			<h1>About page</h1>
			
		<p>Who ? Amina Bouabdallah :) 20 years old, from France. Discovered Ruby on Rails at UPenn, as I took CIS196 (Ruby on Rails) </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1> Contact page </h1>

Contact me at amina.bouabdallah@gmail.com

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>


			<h1>Help page</h1>
			<p>Come on, can't be that hard to play around :) </p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home')%>
	<div class="row">
		<div class="span9">
			<div class="add-padding">
				<div class="center hero-unit">	
					<h1>IDK </h1>
					<h2> - I don't know what this app is ;) </h2>
					
					
					<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
				</div>
			</div>
		</div>


		<div class="span3">
		</div>
	</div>	

app/views/users/new.html.erb
<h1> Sign up page</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f|%>
			<%= render 'shared/error_messages' %> 
			
			<%= f.label :name, "Enter your name" %>
			<%= f.text_field :name %>

			<%= f.label :lastname, "...and your last name" %>
			<%= f.text_field :lastname %>

			<%= f.label :email, "Don't forget the email" %>
			<%= f.text_field :email %>

			<%= f.label :password, "Now a password" %>
			<%= f.password_field :password, placeholder: "Choose a strong one" %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, placeholder: "Enter the same thing as earlier" %>

			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
	<aside class="span4">
		<section>
			<h1> <%= @user.name %>
		</section>
	</aside>
</div>
